import type { Remedy } from "../types";
import { b1Oral } from "./b1-oral";
import { b1Oral2 } from "./b1-oral2";
import { b1Eye } from "./b1-eye";
import { b1Eye2 } from "./b1-eye2";
import { b1Sleep } from "./b1-sleep";
import { b1Sleep2 } from "./b1-sleep2";

/**
 * Illustrated remedies (added in batches from Sep 2026). Every remedy here has a
 * hero illustration at /public/remedies/<slug>.webp (1200x800) and a share crop at
 * /public/remedies/og/<slug>.jpg, generated by scripts/remedy-art/build.mjs.
 */
const withImage = (list: Remedy[]): Remedy[] => list.map((r) => ({ ...r, image: r.image ?? `/remedies/${r.slug}.webp` }));

export const illustratedRemedies: Remedy[] = withImage([
  // Batch 1: oral care, eye care, sleep & stress
  ...b1Oral,
  ...b1Oral2,
  ...b1Eye,
  ...b1Eye2,
  ...b1Sleep,
  ...b1Sleep2,
]);
